# Introductie - Waarom Wiskunde voor AI?

**Mathematical Foundations - IT & Artificial Intelligence**

---

## 1 Leerdoelen van deze les

Na het doorwerken van deze les ben je in staat om uit te leggen waarom wiskunde essentieel is voor AI en Machine Learning. Je kan de drie wiskundige pijlers, namelijk algebra, calculus en statistiek, koppelen aan specifieke onderdelen van een neuraal netwerk. Daarnaast kan je werken met een Python-omgeving waarin NumPy, Matplotlib en Pandas geïnstalleerd zijn. Tot slot kan je de MNIST-dataset laden en de afbeeldingen visualiseren als numerieke arrays.

## 2 Wat is AI en Machine Learning?

### Het fundamentele verschil tussen klassieke programmering en Machine Learning

Bij klassieke programmering schrijf je als programmeur expliciet de regels die het programma moet volgen. Je geeft het programma data en regels, en het programma produceert een antwoord. Denk bijvoorbeeld aan een programma dat bepaalt of een getal even of oneven is: jij schrijft de regel dat een getal even is als het deelbaar is door 2.

Machine Learning draait dit principe om. In plaats van regels te schrijven, geef je het systeem voorbeelden van data samen met de gewenste antwoorden. Het systeem "leert" vervolgens zelf de onderliggende regels. Dit is bijzonder krachtig voor problemen waarbij de regels te complex zijn om handmatig te schrijven, zoals het herkennen van gezichten of het begrijpen van natuurlijke taal.

<center>
<img src="../../_static/img/les1/ML.png" alt="Beschrijving van de afbeelding" width="500px" />
</center>

In [6]:
# Klassieke programmering: we schrijven de regels zelf
def is_even(n):
    return n % 2 == 0

# Test de functie
print(f"Is 4 even? {is_even(4)}")
print(f"Is 7 even? {is_even(7)}")

# Bij Machine Learning zou het systeem deze regel zelf leren
# uit voorbeelden zoals: (2, True), (3, False), (4, True), (5, False), ...
# Hoe dat werkt? Daar heb je wiskunde voor nodig!

Is 4 even? True
Is 7 even? False


### Soorten Machine Learning

Machine Learning kan worden onderverdeeld in drie hoofdcategorieën, elk met hun eigen toepassingen en technieken.

**Supervised Learning** is de meest voorkomende vorm. Hierbij train je een model met gelabelde data, wat betekent dat je voor elk voorbeeld het correcte antwoord meegeeft. Het model leert de relatie tussen input en output. Voorbeelden zijn spamdetectie in e-mails, het herkennen van handgeschreven cijfers, en het voorspellen van huizenprijzen. Dit is ook de techniek die we in deze cursus zullen gebruiken voor onze cijferherkenning.

**Unsupervised Learning** werkt met data zonder labels. Het model probeert zelf structuur en patronen te ontdekken in de data. Dit wordt gebruikt voor het groeperen van klanten met vergelijkbaar koopgedrag, het reduceren van de dimensionaliteit van data, en het detecteren van anomalieën.

**Reinforcement Learning** is een techniek waarbij een agent leert door interactie met een omgeving. De agent ontvangt beloningen of straffen voor zijn acties en leert zo een optimale strategie. Dit wordt toegepast in game AI, robotica en autonome voertuigen.

<center>
<img src="../../_static/img/les1/MLTypes.png" alt="Beschrijving van de afbeelding" width="500px" />
</center>

### AI in het dagelijks leven

Artificial Intelligence is niet langer sciencefiction maar maakt deel uit van ons dagelijks leven. Wanneer Netflix je een film aanbeveelt of Spotify een afspeellijst samenstelt, gebruiken deze diensten ML-algoritmes die jouw kijkgedrag en muziekvoorkeuren analyseren om voorspellingen te doen over wat je leuk zou kunnen vinden.

Je e-mail inbox wordt beschermd door ML-modellen die spam en phishing detecteren door te leren van miljoenen voorbeelden van legitieme en ongewenste berichten. Moderne chatbots zoals ChatGPT zijn gebouwd op grote taalmodellen die getraind zijn op enorme hoeveelheden tekst om menselijke taal te begrijpen en te genereren.

Beeldgeneratie tools zoals DALL-E en Midjourney gebruiken neurale netwerken om nieuwe afbeeldingen te creëren op basis van tekstbeschrijvingen. Zelfrijdende auto's combineren computer vision, sensor fusion en beslissingsalgoritmes om veilig te navigeren in het verkeer.

Al deze toepassingen hebben één ding gemeen: ze zijn gebouwd op een fundament van wiskunde.

## 3 Wat is een Neuraal Netwerk?

### Inspiratie uit de biologie

Het concept van een neuraal netwerk is geïnspireerd door de werking van het menselijk brein. Ons brein bestaat uit miljarden neuronen die met elkaar verbonden zijn via synapsen. Wanneer een neuron voldoende signalen ontvangt van andere neuronen, "vuurt" het en stuurt het een signaal naar de neuronen waarmee het verbonden is.

Kunstmatige neurale netwerken bootsen dit principe na, maar het is belangrijk om te begrijpen dat ze een sterke vereenvoudiging zijn van biologische neurale netwerken. In essentie is een kunstmatig neuraal netwerk een wiskundige functie die input transformeert naar output via een reeks berekeningen. De "intelligentie" komt niet uit mysterieuze processen, maar uit wiskunde: matrixvermenigvuldigingen, niet-lineaire functies en optimalisatie-algoritmes.

<center>
<img src="../../_static/img/les1/Neuron.png" alt="Beschrijving van de afbeelding" width="500px" />
</center>

### De architectuur van een neuraal netwerk

Een neuraal netwerk bestaat uit lagen van neuronen. De eerste laag is de input laag die de ruwe data ontvangt. Voor het herkennen van handgeschreven cijfers is dit een afbeelding van 28 bij 28 pixels, wat neerkomt op 784 inputwaarden.

Tussen de input en output bevinden zich een of meerdere verborgen lagen. In ons voorbeeld gebruiken we één verborgen laag met 128 neuronen. Deze neuronen leren abstracte kenmerken te herkennen, zoals randen, curves en hoeken.

De output laag produceert het eindresultaat. Voor cijferherkenning hebben we 10 output neuronen, één voor elk cijfer van 0 tot 9. Elk output neuron geeft een score die aangeeft hoe waarschijnlijk het is dat de input dat specifieke cijfer voorstelt.

```
Input (784) → Verborgen Laag (128) → Output (10)
   ↓              ↓                    ↓
 pixels      kenmerken              cijfers
```

<center>
<img src="../../_static/img/les1/NeuralNetwork.png" alt="Beschrijving van de afbeelding" width="500px" />
</center>

### De wiskundige bouwstenen

Elk onderdeel van een neuraal netwerk correspondeert met specifieke wiskundige concepten die we in deze cursus zullen behandelen.

De **input data** wordt gerepresenteerd als vectoren en matrices. Een afbeelding is niets meer dan een geordende verzameling getallen, en lineaire algebra geeft ons de tools om hier efficiënt mee te werken.

De **gewichten** zijn de leerbare parameters van het netwerk. Elke verbinding tussen twee neuronen heeft een gewicht, en alle gewichten samen bepalen wat het netwerk "weet". De berekening van output uit input en gewichten gebeurt via matrixvermenigvuldiging.

**Activatiefuncties** voegen niet-lineariteit toe aan het netwerk. Zonder deze functies zou een neuraal netwerk met meerdere lagen wiskundig equivalent zijn aan een netwerk met één laag, waardoor het onmogelijk zou zijn om complexe patronen te leren. We bestuderen functies en hun afgeleiden om te begrijpen hoe deze werken.

De **loss functie** meet hoe ver de voorspelling van het netwerk afwijkt van het correcte antwoord. Dit is een functie die we willen minimaliseren, wat ons brengt bij optimalisatie en statistiek.

Tijdens **training** passen we de gewichten aan om de loss te verlagen. Dit gebeurt via gradient descent, een algoritme dat gebruik maakt van afgeleiden om te bepalen hoe elk gewicht moet worden aangepast.

De **output** van het netwerk interpreteren we als een kansverdeling. Het netwerk geeft voor elk mogelijk antwoord een waarschijnlijkheid, en we kiezen het antwoord met de hoogste kans. Dit vereist kennis van kansrekenen.

In [1]:
import torch
import torch.nn as nn

# Dit is een volledig neuraal netwerk in slechts enkele regels code.
# Het lijkt eenvoudig, maar achter elke regel schuilt wiskunde.
# Tegen les 12 begrijp je precies wat hier gebeurt en kan je dit zelf bouwen!

model = nn.Sequential(
    nn.Linear(784, 128),   # Lineaire transformatie: matrixvermenigvuldiging + bias
    nn.ReLU(),             # Activatiefunctie: niet-lineariteit toevoegen
    nn.Linear(128, 10),    # Nog een lineaire transformatie naar 10 outputs
    nn.Softmax(dim=1)      # Omzetten naar kansen die optellen tot 1
)

# Tel het aantal parameters (gewichten en biases)
totaal_parameters = sum(p.numel() for p in model.parameters())
print(f"Dit model heeft {totaal_parameters:,} leerbare parameters.")
print(f"\nDat zijn {totaal_parameters:,} getallen die we moeten optimaliseren!")
print(f"Hoe vinden we de beste waarden? Met wiskunde.")

Dit model heeft 101,770 leerbare parameters.

Dat zijn 101,770 getallen die we moeten optimaliseren!
Hoe vinden we de beste waarden? Met wiskunde.


## 4 De Drie Pijlers van ML-Wiskunde

De wiskunde achter Machine Learning kan worden onderverdeeld in drie hoofdgebieden. Elk gebied behandelt een fundamenteel aspect van hoe neurale netwerken werken. In de volgende secties verkennen we elk van deze pijlers en zien we hoe ze samenkomen in een neuraal netwerk.

### Pijler 1: Lineaire Algebra

Lineaire algebra is de taal waarin we data representeren en manipuleren. In Machine Learning werken we met grote hoeveelheden data die efficiënt moeten worden opgeslagen en verwerkt. Lineaire algebra biedt hiervoor de perfecte abstracties.

Een **scalar** is een enkel getal, zoals de temperatuur buiten of de prijs van een product. Een **vector** is een geordende lijst van getallen. We kunnen een vector gebruiken om een punt in een ruimte te beschrijven, of om alle eigenschappen van een object te bundelen. Een **matrix** is een rechthoekige tabel van getallen, georganiseerd in rijen en kolommen. Een afbeelding van 28 bij 28 pixels kan worden voorgesteld als een matrix met 28 rijen en 28 kolommen. Een **tensor** is de generalisatie naar hogere dimensies, zoals een kleurenafbeelding met drie kanalen voor rood, groen en blauw.

<center>
<img src="../../_static/img/les1/DataHierarchy.png" alt="Beschrijving van de afbeelding" width="500px" />
</center>

De kracht van lineaire algebra ligt in de operaties die we kunnen uitvoeren. Matrixvermenigvuldiging stelt ons in staat om in één bewerking alle verbindingen tussen twee lagen van een neuraal netwerk te berekenen. Dit is niet alleen wiskundig elegant, maar ook computationeel efficiënt omdat moderne hardware geoptimaliseerd is voor matrixoperaties.

We besteden drie lessen aan lineaire algebra, waarin we vectoren, matrices, matrixoperaties, stelsels van vergelijkingen en speciale matrixeigenschappen behandelen.

In [3]:
import numpy as np

# Een afbeelding is gewoon een matrix van getallen!
# Hier maken we een simpele 5x5 "afbeelding" die een plus-teken voorstelt.

afbeelding = np.array([
    [0,   0,   255, 0,   0  ],
    [0,   0,   255, 0,   0  ],
    [255, 255, 255, 255, 255],
    [0,   0,   255, 0,   0  ],
    [0,   0,   255, 0,   0  ]
])

print("Dit is een afbeelding als matrix:")
print(afbeelding)
print(f"\nDe afbeelding heeft shape {afbeelding.shape}, dus {afbeelding.shape[0]} rijen en {afbeelding.shape[1]} kolommen.")
print(f"In totaal zijn dat {afbeelding.size} pixels oftewel {afbeelding.size} getallen.")

Dit is een afbeelding als matrix:
[[  0   0 255   0   0]
 [  0   0 255   0   0]
 [255 255 255 255 255]
 [  0   0 255   0   0]
 [  0   0 255   0   0]]

De afbeelding heeft shape (5, 5), dus 5 rijen en 5 kolommen.
In totaal zijn dat 25 pixels oftewel 25 getallen.


In [ ]:
import matplotlib.pyplot as plt

# Laten we de matrix visualiseren als een afbeelding
plt.figure(figsize=(4, 4))
plt.imshow(afbeelding, cmap='gray', vmin=0, vmax=255)
plt.title('Een matrix als afbeelding')
plt.colorbar(label='Pixelwaarde')
plt.show()

print("De waarde 0 is zwart, 255 is wit.")
print("Elke pixel is een getal, en de hele afbeelding is een matrix.")

: 

### Pijler 2: Calculus en Optimalisatie

Calculus, en in het bijzonder de studie van afgeleiden, vormt de basis voor hoe neurale netwerken leren. Het centrale idee is verrassend eenvoudig: we definiëren een functie die meet hoe slecht ons netwerk presteert, de zogenaamde loss functie, en dan passen we de gewichten aan om deze functie te minimaliseren.

<center>
<img src="../../_static/img/les1/GradientDescent.png" alt="Beschrijving van de afbeelding" width="500px" />
</center>

De **afgeleide** van een functie vertelt ons hoe snel de functie verandert. Als we een loss functie hebben die afhangt van de gewichten van ons netwerk, dan vertelt de afgeleide ons in welke richting we de gewichten moeten aanpassen om de loss te verlagen. Een positieve afgeleide betekent dat de functie stijgt als we het gewicht verhogen, dus moeten we het gewicht verlagen. Een negatieve afgeleide betekent het omgekeerde.

**Gradient descent** is het algoritme dat deze intuïtie formaliseert. We berekenen de gradiënt, wat de verzameling is van alle partiële afgeleiden, en we nemen een stapje in de tegengestelde richting. Door dit proces vele malen te herhalen, "daalt" het netwerk naar een minimum van de loss functie, vandaar de naam gradient descent.

**Backpropagation** is de techniek waarmee we efficiënt de gradiënt berekenen voor alle gewichten in een netwerk. Het maakt gebruik van de kettingregel uit de calculus om de gradiënt laag per laag terug te propageren vanaf de output naar de input.

We besteden vier lessen aan calculus en optimalisatie, waarin we functies, afgeleiden, activatiefuncties, gradient descent en backpropagation behandelen.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Stel je voor dat de loss van ons netwerk afhangt van één gewicht.
# De loss functie zou er zo uit kunnen zien:

gewicht = np.linspace(-5, 5, 200)
loss = gewicht**2 + 2 * np.sin(gewicht) + 3

# Het doel is om het gewicht te vinden waar de loss minimaal is.

plt.figure(figsize=(10, 5))
plt.plot(gewicht, loss, 'b-', linewidth=2)
plt.xlabel('Gewicht', fontsize=12)
plt.ylabel('Loss (fout)', fontsize=12)
plt.title('Het optimalisatieprobleem: vind de waarde waar de loss minimaal is', fontsize=14)

# Markeer het minimum
min_index = np.argmin(loss)
plt.scatter([gewicht[min_index]], [loss[min_index]], color='red', s=100, zorder=5, label='Minimum')
plt.legend(fontsize=11)
plt.grid(True, alpha=0.3)
plt.show()

print(f"Het minimum ligt ongeveer bij gewicht = {gewicht[min_index]:.2f}")
print(f"De loss op dat punt is {loss[min_index]:.2f}")
print(f"\nMaar hoe vinden we dit minimum systematisch? Met afgeleiden!")

### Pijler 3: Statistiek en Kansrekenen

De derde pijler behandelt onzekerheid. In de echte wereld kunnen we zelden met 100% zekerheid voorspellingen doen. Statistiek en kansrekenen geven ons de wiskundige tools om met deze onzekerheid om te gaan.

**Kansrekenen** stelt ons in staat om de output van een neuraal netwerk te interpreteren als waarschijnlijkheden. In plaats van te zeggen "dit is een 3", zegt het netwerk "de kans dat dit een 3 is, is 70%". Dit is niet alleen informatief, maar ook essentieel voor het trainen van het netwerk.

De **softmax functie** zet de ruwe output van een netwerk om naar een kansverdeling. Elke output wordt een getal tussen 0 en 1, en alle outputs samen tellen op tot 1. Dit correspondeert met de intuïtie dat de kansen van alle mogelijke uitkomsten samen 100% moeten zijn.

**Statistiek** helpt ons om te evalueren hoe goed ons model presteert en hoe betrouwbaar onze resultaten zijn. We kunnen betrouwbaarheidsintervallen berekenen om aan te geven hoe zeker we zijn over de nauwkeurigheid van ons model, en we kunnen hypothesetoetsen gebruiken om te bepalen of een verbetering statistisch significant is of gewoon toeval.

We besteden drie lessen aan statistiek en kansrekenen, waarin we kansvariabelen, kansverdelingen, Bayes' regel, betrouwbaarheidsintervallen en model evaluatie behandelen.

In [ ]:
import numpy as np

# De output van een neuraal netwerk voor cijferherkenning is een kansverdeling.
# Elk getal geeft de kans dat de input dat specifieke cijfer voorstelt.

voorspelling = np.array([0.02, 0.01, 0.05, 0.70, 0.03, 0.08, 0.02, 0.02, 0.04, 0.03])
cijfers = np.arange(10)

print("Output van het neuraal netwerk (kansen per cijfer):")
print()
for cijfer, kans in zip(cijfers, voorspelling):
    balk = '█' * int(kans * 50)
    print(f"  Cijfer {cijfer}: {kans:.2f} {balk}")

print()
print(f"Som van alle kansen: {voorspelling.sum():.2f}")
print(f"\nHet model voorspelt: dit is een {np.argmax(voorspelling)}")
print(f"Met {voorspelling.max()*100:.0f}% zekerheid.")

In [ ]:
import matplotlib.pyplot as plt

# Visualiseer de kansverdeling als staafdiagram

plt.figure(figsize=(10, 5))
kleuren = ['red' if i == np.argmax(voorspelling) else 'steelblue' for i in range(10)]
plt.bar(cijfers, voorspelling, color=kleuren)
plt.xlabel('Cijfer', fontsize=12)
plt.ylabel('Kans', fontsize=12)
plt.title('Output van een neuraal netwerk: een kansverdeling over alle mogelijke cijfers', fontsize=14)
plt.xticks(cijfers)
plt.ylim(0, 1)
plt.grid(axis='y', alpha=0.3)
plt.show()

print("De rode balk toont het cijfer met de hoogste kans.")
print("Dit is de uiteindelijke voorspelling van het netwerk.")

## 5 Onze Rode Draad: MNIST

### Wat is de MNIST dataset?

MNIST staat voor Modified National Institute of Standards and Technology. Het is een dataset van 70.000 handgeschreven cijfers, verzameld van verschillende schrijvers. Elke afbeelding is een cijfer van 0 tot en met 9, getekend in zwart-wit op een raster van 28 bij 28 pixels.

MNIST wordt vaak de "Hello World" van Machine Learning genoemd. Het is complex genoeg om interessante problemen te illustreren, maar eenvoudig genoeg om snel mee te experimenteren. Vrijwel elke nieuwe techniek in deep learning wordt eerst getest op MNIST voordat ze wordt toegepast op complexere datasets.

De dataset is opgesplitst in 60.000 trainingsvoorbeelden en 10.000 testvoorbeelden. We trainen ons model op de trainingsset en evalueren de prestaties op de testset om te zien hoe goed het generaliseert naar nieuwe, ongeziene data.

### Afbeeldingen als getallen

Elke MNIST-afbeelding is een raster van 28 bij 28 pixels. Elke pixel heeft een waarde tussen 0 en 255, waarbij 0 volledig zwart is en 255 volledig wit. Dit betekent dat elke afbeelding kan worden voorgesteld als een matrix van 28 bij 28 getallen, of equivalent, als een vector van 784 getallen wanneer we de rijen achter elkaar plaatsen.

Deze numerieke representatie is precies wat een neuraal netwerk nodig heeft. Het netwerk ziet geen "afbeelding" in de menselijke zin, maar een lange lijst van 784 getallen. Het is de taak van het netwerk om te leren welke patronen in deze getallen corresponderen met welke cijfers.

In [ ]:
from sklearn.datasets import fetch_openml
import numpy as np

# Laad de MNIST dataset
# Dit kan even duren bij de eerste keer omdat de data moet worden gedownload.

print("MNIST dataset laden...")
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
X, y = mnist.data, mnist.target.astype(int)

print("\nDataset geladen!")
print(f"\nAantal afbeeldingen: {X.shape[0]:,}")
print(f"Pixels per afbeelding: {X.shape[1]}")
print(f"Dat is {int(np.sqrt(X.shape[1]))} × {int(np.sqrt(X.shape[1]))} pixels.")
print(f"\nUnieke labels: {np.unique(y)}")
print(f"Datatype van pixels: {X.dtype}")
print(f"Pixelwaarden variëren van {X.min():.0f} tot {X.max():.0f}.")

MNIST dataset laden...

Dataset geladen!

Aantal afbeeldingen: 70,000
Pixels per afbeelding: 784
Dat is 28 × 28 pixels.

Unieke labels: [0 1 2 3 4 5 6 7 8 9]
Datatype van pixels: int64
Pixelwaarden variëren van 0 tot 255.


In [ ]:
import matplotlib.pyplot as plt

# Laten we een paar voorbeelden bekijken

fig, axes = plt.subplots(2, 5, figsize=(12, 5))
fig.suptitle('Voorbeelden uit de MNIST dataset', fontsize=16)

for i, ax in enumerate(axes.flat):
    # Neem een willekeurig voorbeeld
    index = np.random.randint(0, len(X))
    
    # Reshape van vector (784,) naar matrix (28, 28)
    afbeelding = X[index].reshape(28, 28)
    
    ax.imshow(afbeelding, cmap='gray')
    ax.set_title(f'Label: {y[index]}', fontsize=12)
    ax.axis('off')

plt.tight_layout()
plt.show()

print("Elk van deze afbeeldingen is een matrix van 28×28 getallen.")
print("Het netwerk moet leren om van deze getallen naar het juiste label te gaan.")

In [ ]:
# Laten we één afbeelding in detail bekijken

index = 0
afbeelding = X[index].reshape(28, 28)
label = y[index]

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Links: de afbeelding
axes[0].imshow(afbeelding, cmap='gray')
axes[0].set_title(f'Afbeelding (label: {label})', fontsize=14)
axes[0].axis('off')

# Rechts: de numerieke waarden met kleurcodering
im = axes[1].imshow(afbeelding, cmap='viridis')
axes[1].set_title('Pixelwaarden (0-255)', fontsize=14)
plt.colorbar(im, ax=axes[1], label='Pixelwaarde')

plt.tight_layout()
plt.show()

print(f"\nDeze afbeelding is het cijfer {label}.")
print(f"De afbeelding is opgeslagen als {afbeelding.size} getallen.")
print(f"Gemiddelde pixelwaarde: {afbeelding.mean():.1f}")
print(f"Aantal niet-zwarte pixels: {np.sum(afbeelding > 0)}")

In [ ]:
# Bekijk een klein stukje van de ruwe data

print("De eerste 14×14 pixels van de afbeelding als getallen:")
print()

# Print een deel van de matrix met nette opmaak
for rij in afbeelding[:14, :14]:
    print(' '.join(f'{int(pixel):3d}' for pixel in rij))

print("\n...")
print("\nDit is wat het neuraal netwerk 'ziet': gewoon getallen.")
print("De uitdaging is om te leren welke patronen in deze getallen bij welk cijfer horen.")

### Wat gaan we bereiken?

Aan het einde van deze cursus bouwen we een volledig functionerend neuraal netwerk dat handgeschreven cijfers kan herkennen met een nauwkeurigheid van ongeveer 95%. Het bijzondere is dat we dit netwerk bouwen met alleen NumPy, zonder gebruik te maken van frameworks zoals PyTorch of TensorFlow.

Dit betekent dat je elke berekening, van de forward pass tot de backpropagation, zelf implementeert en begrijpt. Je zal zien hoe matrixvermenigvuldiging de forward pass aandrijft, hoe de kettingregel de gradiënten berekent, en hoe gradient descent de gewichten aanpast.

Daarna vergelijken we onze implementatie met een PyTorch versie om te zien hoe professionele frameworks dezelfde concepten abstraheren. Je zal ontdekken dat de onderliggende wiskunde identiek is; de frameworks maken het alleen makkelijker en sneller.

## 6 Samenvatting en Vooruitblik

### Kernboodschap

> **"Een neuraal netwerk is geen magie. Het is lineaire algebra, calculus en statistiek, slim gecombineerd."**

### Wat hebben we geleerd?

In deze introductie hebben we de fundamenten gelegd voor de rest van de cursus. We hebben gezien dat Machine Learning een ander paradigma is dan klassieke programmering: in plaats van regels te schrijven, laten we het systeem zelf regels leren uit data.

Een neuraal netwerk is een wiskundige functie die is opgebouwd uit lagen van neuronen. Elke laag voert berekeningen uit met behulp van matrixvermenigvuldigingen en activatiefuncties. Het netwerk leert door de gewichten aan te passen met gradient descent, een optimalisatie-algoritme dat gebruik maakt van afgeleiden.

De drie pijlers van ML-wiskunde zijn lineaire algebra voor datarepresentatie en transformatie, calculus voor leren en optimalisatie, en statistiek voor het omgaan met onzekerheid en het evalueren van modellen.

We hebben kennisgemaakt met de MNIST dataset, onze rode draad doorheen de cursus. Elke afbeelding is een matrix van 28 bij 28 pixels, en ons doel is om een netwerk te bouwen dat leert welk cijfer elke afbeelding voorstelt.

### Checklist leerdoelen

Neem even de tijd om te reflecteren over wat je hebt geleerd. Kan je de volgende vragen beantwoorden?

1. Wat is het verschil tussen klassieke programmering en Machine Learning?

2. Welke drie wiskundige disciplines vormen de basis van ML, en waarvoor wordt elk gebruikt?

3. Wat is een neuraal netwerk in wiskundige termen?

4. Hoe wordt een MNIST-afbeelding gerepresenteerd als data?

Als je deze vragen kan beantwoorden, ben je klaar voor de volgende les!

### Volgende les

In les 2 duiken we in de lineaire algebra. We leren wat vectoren en matrices zijn, hoe we ze kunnen manipuleren, en hoe we ze gebruiken om data te representeren. We zullen zien hoe een MNIST-afbeelding kan worden voorgesteld als een vector en hoe we met deze vectoren kunnen rekenen.

Zorg dat je de labo-oefeningen van deze les maakt voordat je aan les 2 begint. Ze helpen je om vertrouwd te raken met NumPy en de MNIST dataset.